#!/bin/bash
# Manual Production Setup Instructions

echo "==================================================================="
echo "  SMART-Admin Production Setup - Manual Instructions"
echo "==================================================================="
echo ""
echo "Step 1: Stop Development Mode"
echo "-------------------------------------------------------------------"
echo "pkill -f 'tsx.*server'"
echo "pkill -f 'UniversalSMARTAgent'"
echo "pkill -f 'npm run dev'"
echo ""
echo "Step 2: Install PM2 (if not installed)"
echo "-------------------------------------------------------------------"
echo "npm install -g pm2"
echo ""
echo "Step 3: Build Frontend"
echo "-------------------------------------------------------------------"
echo "npx vite build"
echo ""
echo "Step 4: Start Production Services"
echo "-------------------------------------------------------------------"
echo "pm2 start ecosystem.config.cjs"
echo ""
echo "Step 5: Save PM2 Configuration (optional - auto-start on reboot)"
echo "-------------------------------------------------------------------"
echo "pm2 save"
echo "pm2 startup   # Follow the instructions it gives you"
echo ""
echo "==================================================================="
echo "  Useful PM2 Commands"
echo "==================================================================="
echo ""
echo "pm2 status                  # View running services"
echo "pm2 logs                    # View all logs in real-time"
echo "pm2 logs smart-admin-server # View server logs only"
echo "pm2 logs smart-node-agent   # View agent logs only"
echo "pm2 monit                   # Monitor CPU/Memory usage"
echo "pm2 restart all             # Restart all services"
echo "pm2 stop all                # Stop all services"
echo "pm2 delete all              # Remove all services"
echo ""
echo "==================================================================="
echo "  Access Points"
echo "==================================================================="
echo ""
echo "Web Interface: http://localhost:5001"
echo "UDP Discovery: Port 8765"
echo ""
